### ISSUE TITLE
Ionic integration compatible?

### ISSUE THREAD

**Issue by jllaurado** [capacitor-community/fcm#100]
**Describe the bug**
I'm trying to use the module on ionic with capacitor and it give me an error. Following your instructions I've added an:

import { FCM } from '@capacitor-community/fcm';

in my fcm service but I'm not able to build, with the error:

Error: src/app/services/push.service.ts:12:21 - error TS2307: Cannot find module '@capacitor-community/fcm' or its corresponding type declarations.

12 import { FCM } from '@capacitor-community/fcm';
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
I've installed the module using:

$ npm i @capacitor-community/fcm

It seems trivial, but is it possible that it's imcompatible with ionic this module?

thanks.

**Comment by jcesarmobile** [comment]
I can't reproduce using latest ionic, capacitor and plugin, so it's probably fixed or related to some dependency in your project.

If you still face the issue, please, create a new one and provide a sample app where the issue can be reproduced.
