### ISSUE TITLE
Getting encoded JWT instead of token on Android

### ISSUE THREAD

**Issue by rukafasha** [capacitor-community/fcm#104]
Hi everyone, I am having issue with getting token on Android. On iOS works fine.

**Describe the bug**
I am not receiving correct FCM token on Android. Instead, I am receiving JWT. 

**To Reproduce**
1. Call FCM.getToken()
2. Token is received
3. Expected length is 64 characters
4. Length is > 130 characters
5. Turns out that this is encoded FCM JWT token

**Expected behavior**
I should receive FCM token, as on iOS and not JWT

**Comment by cyril-colin** [comment]
Hi ! this problem as already been reported here : https://github.com/capacitor-community/fcm/issues/99 ;-)

**Comment by rukafasha** [comment]
You da real MVP! :)
Many thanks, solved it in a minute!
