### ISSUE TITLE
Invalid Registration on Ionic-vue Android

### ISSUE THREAD

**Issue by fahadalidev** [capacitor-community/fcm#113]
**Describe the bug**

I'm using ionic-vue and fcm is working fine on ios. But on android returned token cannot using to send the notification. It always says 
"{"multicast_id":62279612766420011,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}"
while sending notification against android returned token.

**Comment by xeaiow** [comment]
I same issue, did you solved it?

**Comment by shing1630** [comment]
I have the same problem too. The android token string is way too long compare with the ios one.
Anyone solve it?

**Comment by shing1630** [comment]
> I have the same problem too. The android token string is way too long compare with the ios one. Anyone solve it?
It returns the JWT in android.
we can find the workaround here: https://github.com/capacitor-community/fcm/issues/99

**Comment by jcesarmobile** [comment]
should be fixed by https://github.com/capacitor-community/fcm/pull/111
