### ISSUE TITLE
question: How does this library compare versus the official `@capacitor/push-notifications` plugin?

### ISSUE THREAD

**Issue by tafelnl** [capacitor-community/fcm#115]
I am confused as to what the benefit is for using this library over the official `@capacitor/push-notifications` plugin.

I tried to look for it in the docs/issues, and the only thing I found about it was this comment (https://github.com/capacitor-community/fcm/issues/11#issuecomment-515796247) of you (@stewones) saying

> Capacitor will never send you fcm tokens, that’s why I created this plugin.

But, actually, the Capacitor plugin _does_ support retrieving the token (maybe it wasn't at the time of your writing, but it is now): https://capacitorjs.com/docs/apis/push-notifications#token

So that leaves me wondering: what is the benefit of this plugin?

**Comment by allard-potma** [comment]
The official does not support subscribing to topics (yet).

**Comment by jcesarmobile** [comment]
@capacitor/push-notifications uses FCM on Android and APNS on iOS
@capacitor-community/fcm uses FCM on both Android and iOS

The token you linked is going to be an APNS token on iOS, unless you [follow this guide](https://capacitorjs.com/docs/guides/push-notifications-firebase) to integrate FCM into your iOS app, that would make it possible to get a FCM token on iOS without needing @capacitor-community/fcm.

@capacitor-community/fcm has some methods that @capacitor/push-notifications doesn't have, like the mentioned about subscribing to topics.

**Comment by stewones** [comment]
Thanks for explaining @jcesarmobile
