### ISSUE TITLE
Function onTokenRefresh

### ISSUE THREAD

**Issue by josuelmm** [capacitor-community/fcm#116]
Good day, in the plugin
https://www.npmjs.com/package/cordova-plugin-fcm-with-dependecy-updated
Exists a function for regenerate a new token. 
Is it possible to do the same with this plugin?

**Comment by josuelmm** [comment]
Function ready https://github.com/capacitor-community/fcm/pull/117

**Comment by jaletechs** [comment]
@josuelmm That is awesome! Any idea when that PR would be merged and a new version released?

**Comment by jcesarmobile** [comment]
closing as the linked PR was merged
