### ISSUE TITLE
The refreshToken function returns the Firebase JWT session token instead of the FCM token

### ISSUE THREAD

**Issue by bipoza** [capacitor-community/fcm#137]
**Describe the bug**
The refreshToken function returns the Firebase JWT session token instead of the FCM token.

**To Reproduce**
To reproduce it, just compare the value of the function getToken() and refreshToken().

- This is an example of a valid token: cKtVpkq3RAmImWlhFX1fjk:APA91bFyjkgVa3T6kURNhxD8uwsBEyqekQyzfMFGZIRO9tUnJsx6v4mm1tQQKUp5QNsueDzC3beMHbgusfIWI_P8w9X76swe0HceF168zQsYGcPMvSDNFI_QoL_hupUtDcempmK3O8bP

- This is an example of a JWT token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

**Expected behavior**
What is expected with the refreshToken function is to delete the old token and get a new one.

**Comment by FilipKrizanic** [comment]
Is this on iOS or also on Android?
I am just asking because on iOS APNs token is returned whereas on Android PushID.
If this is the case then you could get some info on "closed late to the party" answer: https://github.com/capacitor-community/fcm/issues/99#issuecomment-1413657559
