### ISSUE TITLE
Type 'NSNotification.Name?' has no member 'capacitorDidRegisterForRemoteNotifications' (ios)

### ISSUE THREAD

**Issue by devexpert9** [capacitor-community/fcm#152]
capacitorcommunityFcm plugin 

plugin.swift

public override func load() {
        if (FirebaseApp.app() == nil) {
            FirebaseApp.configure();
        }
        Messaging.messaging().delegate = self
        NotificationCenter.default.addObserver(self, selector: #selector(self.didRegisterWithToken(notification:)), name: .capacitorDidRegisterForRemoteNotifications, object: nil)
    }

this error is occurred during creating the iOS build 
*Type 'NSNotification.Name?' has no member 'capacitorDidRegisterForRemoteNotifications'*

Please help me out of this....

**Comment by jcesarmobile** [comment]
what's your capacitor version?
latest version of the plugin requires capacitor 5

**Comment by jcesarmobile** [comment]
Closing as there was no response
