### ISSUE TITLE
Fail  to subscribe to topic

### ISSUE THREAD

**Issue by golontico** [capacitor-community/fcm#50]
I try to subscribe to an X token in Android and I can't make it happen and the catch doesn't give me any results

I have the latest version 1.0.8 installed, synchronize the project, recreate it, add part of my implementation.

PushNotifications.register()
      .then(() => {
        fcm
          .subscribeTo({ topic: topicName })
          .then(r => console.log('Suscrito a topic', topicName))
          .catch(err => console.log('Error', err));
      })
      .catch((err) => {
      console.log('Topic ' + topicName + '!');
      console.log('Error catch subscribe to topic', JSON.stringify(err));
    }
      );

the anwser of Android Studio "error catch" JSON.stringify(err) shown
" typeerror cannot read property 'toSubscribe' of undefined "

I try with the example code(https://github.com/capacitor-community/fcm/blob/master/example/src/app/home/home.page.ts) a shows the same error

![error](https://user-images.githubusercontent.com/3815086/87851028-2218b580-c8b2-11ea-9233-beb603a31c1d.JPG)

**Comment by golontico** [comment]
Sorry was my fault i did not add
import com.getcapacitor.community.fcm.FCMPlugin; and then inside the init callback add(FCMPlugin.class);

**Comment by vigamage** [comment]
hi @golontico Can you pls add a sample on how to do this initialization? In the documentation, I cannot see it is mentioned
