### ISSUE TITLE
TypeError: Cannot read property 'subscribeTo' of undefined

### ISSUE THREAD

**Issue by tolutronics** [capacitor-community/fcm#53]
**Describe the bug**
Whenever i tried to subscribe to a topic or get Token, i get the error 
TypeError: Cannot read property 'subscribeTo' of undefined
i am using ionic framework

**Comment by grallc** [comment]
Same here :/

**Comment by stewwan** [comment]
that information is not enough. how to reproduce the problem? have you tried the example included in this repo? have you [searched for this kind of issue](https://github.com/capacitor-community/fcm/issues?q=is%3Aissue+subscribe)? please open a new issue with more info

**Comment by tolutronics** [comment]
grallc , please check your set up...in my case i ignore this part

on your MainActivity.java file add import com.getcapacitor.community.fcm.FCMPlugin; and then inside the init callback add(FCMPlugin.class);

but after following this, it worked perfectly
