### ISSUE TITLE
Import in AndroidManifest

### ISSUE THREAD

**Issue by fertandil87** [capacitor-community/fcm#54]
Following the setup process for android, when I add the import, it cant found the community path:

import com.getcapacitor.community.fcm.FCMPlugin;

the community word is in red

The app looks like it works fine, also the plugin

any ideas? thanks

**Comment by stewwan** [comment]
Did you run `npx cap sync android` after the plugin installation?

**Comment by fertandil87** [comment]
Yes I tried all commands, but today after reopen the IDE, the error disappeared, so closing it. Sorry
