### ISSUE TITLE
Fcm topics don't handling push notification when app was killed

### ISSUE THREAD

**Issue by ak1dos** [capacitor-community/fcm#55]
I have a problem with the subscription via topics. Using capacitor's Push Notification plugin with the fcm plugin I can't receive notifications when the app is closed. If I send a direct notification to the token generated by the Push Notification plugin, the notification also arrives at closed application. After the first direct submission, the application also begins to receive notifications via topics that are closed until a new token is generated.

**Comment by stewones** [comment]
you need to configure `presentationOptions`  on your capacitor json/ts
please refer to the capacitor docs
https://capacitorjs.com/docs/apis/push-notifications#examples
