### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/fcm#59]
Capacitor 3 is currently in alpha. It would be great if this plugin released a Capacitor 3 compatible version around the same time as the full release. 

The official Capacitor [Push Notifications Plugin](https://github.com/ionic-team/capacitor-plugins/pull/126) was just updated to be v3 compatible. Once a new version is pushed to npm, we'd be able to start the work on migrating over. 

Happy to help out if I can 😄

**Comment by stewones** [comment]
I will as soon as full release is out

**Comment by charlouze** [comment]
For those who are currently building an app and want to use capacitor v3, I've been able to use this plugin :
```typescript
import { FCMProtocol } from '@capacitor-community/fcm';
import { registerPlugin } from '@capacitor/core';

const Fcm = registerPlugin<FCMProtocol>(
  'FCMPlugin',
  {},
);
```

**Comment by EinfachHans** [comment]
@stewones Maybe you can already do this in a separate Branch, so we can use tis Branch until V3 is out of RC state?

**Comment by stanstanov** [comment]
I waiting this plugin for capacitor V3 too

**Comment by savgiannis** [comment]
Hi,

Capacitor 3 just was released. Maybe it's time!

**Comment by aechan** [comment]
Can someone please update this for v3? This is the last plugin we're using that hasn't been updated yet.

**Comment by kyleabens** [comment]
> For those who are currently building an app and want to use capacitor v3, I've been able to use this plugin :
> 
> ```ts
> import { FCMProtocol } from '@capacitor-community/fcm';
> import { registerPlugin } from '@capacitor/core';
> 
> const Fcm = registerPlugin<FCMProtocol>(
>   'FCMPlugin',
>   {},
> );
> ```

Unfortunately this did not work for me.  Still getting "Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0" when I try to build in xcode.  Am I missing something?

**Comment by aechan** [comment]
@kyleabens that issue is solved by setting the deployment target for the capacitor fcm project to 12.0 in Xcode. Usually a warning will pop up in the issues menu after a failed build that says something like “Update project to recommended settings” and accepting all the recommended settings will allow you to build.

**Comment by kyleabens** [comment]
@aechan Thats the thing I have the deployment target set to 12.0 in xocde and I get this error and another saying No such module found ‘Capacitor’

**Comment by Nazirovich** [comment]
Hello!! 

any update about upgrading it to Capacitor 3 ?!

**Comment by stewones** [comment]
I'm too busy right now, always open for reviewing and testing PRs though.

**Comment by hemangsk** [comment]
@stewones , I've opened a PR at https://github.com/capacitor-community/fcm/pull/76 for v3 support. Could you please take a look?

**Comment by stewones** [comment]
released on v2 which also supports Firebase 8

**Comment by somq** [comment]
> > For those who are currently building an app and want to use capacitor v3, I've been able to use this plugin :
> > ```ts
> > import { FCMProtocol } from '@capacitor-community/fcm';
> > import { registerPlugin } from '@capacitor/core';
> > 
> > const Fcm = registerPlugin<FCMProtocol>(
> >   'FCMPlugin',
> >   {},
> > );
> > ```
> 
> Unfortunately this did not work for me. Still getting "Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0" when I try to build in xcode. Am I missing something?

Type has changed in latest version(s) for info. (`v2.0.2`)

```ts
import { FCMPlugin } from '@capacitor-community/fcm'
import { registerPlugin } from '@capacitor/core';

const fcm = registerPlugin<FCMPlugin>(
  'FCMPlugin',
  {},
);
```
