### ISSUE TITLE
Capacitor update now FCM to iOS no longer working - old capacitor-fcm package

### ISSUE THREAD

**Issue by madmacc** [capacitor-community/fcm#61]
I updated capacitor to the latest version (2.4.6) from 1.1.1 for @capacitor/ios only. I left the rest at 1.1.1.
In order to resolve some swift compiler errors in the latest Xcode.

I have released the app to the store and FCM to iOS devices does not seem to be working.
It says in the FCM dashboard that 22 have been sent to iOS (should be around 1000) and none of my iOS devices have received them. It still works fine for Android.

I am using the package capacitor-fcm v0.0.7.

I know this has now been replaced with @capacitor-community/fcm as I have used that in another project. https://www.npmjs.com/package/@capacitor-community/fcm

Do I have to downgrade Capacitor or upgrade to the new fcm package or should capacitor-fcm still work with capacitor 2.4.6?

**Comment by stewones** [comment]
I think it's easier if you upgrade to the community version of fcm

capacitor-fcm is deprecated. to be able to use it you would have to downgrade capacitor

**Comment by stewones** [comment]
Not to mention that capacitor 3 is coming (now in beta) Soon there will be a new major version of fcm plugin 😅 as soon as final v3 is out. hopefully with no breaking changes

**Comment by madmacc** [comment]
> Not to mention that capacitor 3 is coming (now in beta) Soon there will be a new major version of fcm plugin 😅 as soon as final v3 is out. hopefully with no breaking changes

I await with bated breath

Thanks for the reply.  Good to get an answer direct from the main (fcm) man.

**Comment by stewones** [comment]
v2 for capacitor v3 and firebase 8 has been just released
