### ISSUE TITLE
Not receiving any Push notification

### ISSUE THREAD

**Issue by aabanaag** [capacitor-community/fcm#66]
**Describe the bug**
I'm not receiving any push notification from console. I got the correct token the one for FCM not the APNS. 

**To Reproduce**
I followed the steps, checked the demo also

**Expected behavior**
Should be able to receive a notif even a log on the console

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12 pro
 - OS: [e.g. iOS8.1] iOS 14

**Additional context**
Ionic:

   Ionic CLI       : 6.12.3 (/Users/jongbanaag/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.1.0

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.1 (/Users/jongbanaag/.nvm/versions/node/v14.15.1/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur

**Comment by Cyral** [comment]
Make sure you have the app closed. I literally spent hours on this when I set up FCM before I realized that push notifications only work if the app is not opened (it can still be running, but the user needs to be in another app or on the homescreen). You can setup notifications to always come through with a setting though I think.

**Comment by aabanaag** [comment]
what, so the app should be closed?

**Comment by aabanaag** [comment]
Wow, I tested it and it worked! thanks but is how to configure it to work even if the app is in foreground?

**Comment by Cyral** [comment]
Honestly I forget what I did, it's been a while. Google around for how to enable push notifications when the app is in the foreground. I think the solution is different for android and ios.

**Comment by aabanaag** [comment]
ok. Thank you!

**Comment by aabanaag** [comment]
This is fixed, the issue was I have multiple plugins for local-notifications for some reason if caused conflict which caused the pushNotificationReceived to not trigger.
