### ISSUE TITLE
FirebaseCore was removed and is still needed by the code the plugin injects

### ISSUE THREAD

**Issue by cgadam** [capacitor-community/fcm#69]
**Describe the bug**
The removal of `FirebaseCore` here:
https://github.com/capacitor-community/fcm/commit/38f186b09525ee681360b4437ed38c1cc57cb981#r51330784
is causing compilation issues as the code the plugin injects actually uses it.

**To Reproduce**
1. Install version fcm `v1.1.1` into existing project
2. Try to compile using XCode
3. You still get compilation issues.

**Expected behavior**
No compilation issues

**Comment by stewones** [comment]
Your existing project might have some plugin which requires it, but fcm itself doesn't. Did you try adding FirebaseCore in your app pod?

**Comment by cgadam** [comment]
@stewones , yep, once adding to my pod, it did worked.

Turns out `Firebase Core` is still being used by the code injected by the plugin here:
https://github.com/capacitor-community/fcm/blob/master/ios/Plugin/Plugin/Plugin.swift#L6

And if you remove `Firebase Core` you won’t be able to do:
https://github.com/capacitor-community/fcm/blob/master/ios/Plugin/Plugin/Plugin.swift#L21

**Comment by cgadam** [comment]
@stewones `FirebaseCore` should probably be also removed from.. https://github.com/capacitor-community/fcm/blob/master/CapacitorCommunityFcm.podspec#L13 ? I guess.

**Comment by stewones** [comment]
> @stewones `FirebaseCore` should probably be also removed from.. https://github.com/capacitor-community/fcm/blob/master/CapacitorCommunityFcm.podspec#L13 ? I guess.

Yeah, I will patch asap

**Comment by stewones** [comment]
@cgadam can you please try a fresh install from 1.1.2 ?

I did test with the example inside this project and it worked just fine. the reason I removed `FirebaseCore` from the plugin podspec is because it's already being installed as a peer dependency by `FirebaseMessaging` as you can see in here

https://cocoapods.org/pods/FirebaseMessaging

I'm closing for now but feel free to reopen

Thank you
