### ISSUE TITLE
Update iOS target to 12.1 for Capacitor 3

### ISSUE THREAD

**Issue by Cyral** [capacitor-community/fcm#70]
Capacitor 3 requires iOS 12.1, so this plugin results in a compilation error:

```/app/node_modules/@capacitor-community/fcm/ios/Plugin/Plugin/Plugin.swift:2:8: Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0```

The target can be adjusted in XCode manually but is lost on every `cap sync`

(Maybe I meant 12.0 instead of 12.1 actually, but xcode only let me pick 12.1)

**Comment by phoenix503** [comment]
Yes , i am facing the same issue .
Please update on this

**Comment by Nikita-schetko** [comment]
Guys, need your help. Same issue here;
<img width="122" alt="Снимок экрана 2021-05-28 в 20 00 41" src="https://user-images.githubusercontent.com/8004255/120018175-753db780-bfef-11eb-837d-e93cf3c08717.png">

**Comment by kinghong88** [comment]
me, too.
Please update on this

**Comment by SyFlo** [comment]
same issue here. please let me know if there is a solution.

**Comment by gwennhester** [comment]
getting this issue as well. any solutions?

**Comment by Cyral** [comment]
This library seems dead. Someone should check out this tutorial on using FCM in Capacitor without any libraries: https://capacitorjs.com/docs/guides/push-notifications-firebase#required-dependencies Not sure if it still works but I will try it at some point, looks pretty straightforward to add notification support as long as you don't need FCM groups or anything that this library provides.

**Comment by phoenix503** [comment]
Any idea how to use topic messaging in capacitor push notifications plugin ?

**Comment by jacewardell** [comment]
I'm having this same issue, but switching to Capacitor's built-in library isn't an option because it doesn't support topics. Does anyone else know of solutions that support topics?

**Comment by ptmkenny** [comment]
@Cyral I don't think it's fair to call this library dead when the [maintainer is busy but willing to review pull requests](https://github.com/capacitor-community/fcm/issues/59#issuecomment-853944331).  This is a community library, so people are welcome to contribute to help keep things up to date.

I recently followed the tutorial you mentioned, but it is for capacitor v2, not v3 (yes, the page says v3, but the information hasn't been updated yet for all the changes that were made in v3); for v3, you need to follow the [plugin docs](https://capacitorjs.com/docs/apis/push-notifications).

**Comment by stewones** [comment]
v2 for cap3 has been released
