### ISSUE TITLE
iOS - no valid aps-environment entitlement string found for application

### ISSUE THREAD

**Issue by sakdeniz** [capacitor-community/fcm#73]
I made FCM community integration (v1.1.1) to my iOS App. I enabled push notification on XCode. I also created the necessary provisioning files from the iOS Developer site (iOS Distribution). Despite trying all kinds of things, I get the following message when testing app on BrowserStack.

"no valid aps-environment entitlement string found for application"

I also checked the contents of the ipa file and verified that the string "aps-environment" is in the file.

Is this a bug or am I missing something?

Environment
Mac OS Big Sur
XCode 12.5
Capacitorjs 2.4.6
FCM Community 1.1.1

**Comment by stewones** [comment]
you're missing something
