### ISSUE TITLE
Android works fine but iOS doesn't

### ISSUE THREAD

**Issue by ncolella** [capacitor-community/fcm#74]
I follow every step in readme, Android works fine. IOS receives token with 
```

 PushNotifications.addListener('registration', (token) => {
                console.log('FB token', token.value);
            });
```

But this method is not triggered 

`  PushNotifications.addListener('pushNotificationReceived', (notification) => {
                console.log('FB message', notification.body);
                // alert('FB message: ' + message.body);
                this.doLocalNotif(notification);
            });
`

Any ideas? Any missing configuration?

**Comment by stewones** [comment]
Use v1.1.0

Current version is broken

**Comment by ncolella** [comment]
> Use v1.1.0
> 
> Current version is broken

Hello, thank you for your answer. I tried to install "@capacitor-community/fcm": "^1.1.0", but Android doesn't work now. Should I change some configuration?

**Comment by stewones** [comment]
@ncolella just released v1.1.2 with a fix for a bug introduced in 1.1.1 
can you try again?
Thank you

**Comment by magiclockers** [comment]
using v1.1.2, IOS not working😭

**Comment by stewones** [comment]
@magiclockers v2 with support for cap3 has been released
