### ISSUE TITLE
Unrecognised member "token"

### ISSUE THREAD

**Issue by jprinsloo** [capacitor-community/fcm#77]
After upgrading the fcm plugin to `2.0.0`, Xcode fails to recognise the member `token` in the Plugin.swift file.

`Value of type 'Messaging' has no member 'token'` on `line 62`.

![Screenshot 2021-06-15 at 10 45 58](https://user-images.githubusercontent.com/16095672/122022504-f1454700-cdc6-11eb-8206-b83472182718.png)

I have followed the iOS setup procedure as stipulated in the docs. Any assistance would be appreciated.

**Comment by stewones** [comment]
check your Podfile.lock, we have upgrade firebase so it *must* show references of  FirebaseMessaging 8

try to

- cd ios/App
- pod cache clean
- pod install

**Comment by jprinsloo** [comment]
As a closing comment, I had to run `pod update`. Thanks for the assistance.
