### ISSUE TITLE
didReceiveRegistrationToken Error

### ISSUE THREAD

**Issue by mattnickcodes** [capacitor-community/fcm#79]
After installation of @capacitor/push-notifications and @capacitor-community/fcm I am able to receive push notifications but I am not able to receive a registration token to send messages to individual users. 

Here is the error I'm getting:

- [Firebase/Messaging][I-FCM002023] The object <FCMPlugin: 0x282382dc0> does not respond to -messaging:didReceiveRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.

**Comment by stewones** [comment]
I suspect you didn't update the AppDelegate for Capacitor v3

Take a look in the example of this repo

https://github.com/capacitor-community/fcm/blob/50ae478d3e4a6a70b3c973dc9c18a158a615e2a8/example/ios/App/App/AppDelegate.swift#L71

**Comment by mattnickcodes** [comment]
This is a fresh project generated with capacitor 3, my AppDelegate file is untouched and exactly the same as the example.

**Comment by stewones** [comment]
Can you provide a reproducible example?

**Comment by mattnickcodes** [comment]
The solution is making sure the FCM.getToken() function is not called/triggered by any of the PushNotifications functions.

The code here causes that error code. I believe it happens because the registration event is being fired before FCM initializes.
`PushNotifications.addListener('registration', () => {
              FCM.getToken().then((token: any)=>this.saveToken(token.value))
            });`

**Comment by stewones** [comment]
Glad you figured it out.
