### ISSUE TITLE
Completely not working anymore (on Android)

### ISSUE THREAD

**Issue by kmschott** [capacitor-community/fcm#80]
First of all, please update the docs (also on npm), the example and the syntax + how to bind the module is outdated.

Second, if I use the plugin on Android I get JUnit version errors or in the current version that the module was not found and a lot of compile errors. Please update the docs and fix the bugs on latest Android version.

I use Vue.js (Quasar) with Capacitor 2

**Comment by stewones** [comment]
Can you send a PR?

**Comment by stewones** [comment]
This kind of attitude is unacceptable, this is a community plugin, feel free to contribute. 

Also if you're using Capacitor v2 you must use FCM 1.x

**Comment by kmschott** [comment]
Why are you closing the bug report? The problem still exists.
