### ISSUE TITLE
warning in MainActivity.java after suggested changes

### ISSUE THREAD

**Issue by DDholiyan** [capacitor-community/fcm#86]
Note: D:\addlance\android\app\src\main\java\io\ionic\starter\MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

This warning is showing during app run via android studio.

Note:- I am using same code as suggested in MainActivity.java file.

**Comment by stewones** [comment]
can you please try on latest capacitor + plugin ?
