### ISSUE TITLE
question: Do we need 'FirebaseCore' & 'Firebase/Messaging' pods?

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/fcm#94]
I did a big cleanup of my Capacitor app upgrading to v3.x.

I saw I still have these in my pod file:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/3253920/135940516-e30921c4-560f-431a-8c49-3fa59425613e.png">

When it comes just to FCM, should I get rid of them?

**Comment by stewones** [comment]
no you don't need to put anything extra in your *app's* podfile in order to use this fcm plugin.
see the [example app](https://github.com/capacitor-community/fcm/blob/master/example/ios/App/Podfile) as reference
