### ISSUE TITLE
question: Do we need to edit AppDelegate.swift?

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/fcm#96]
Some things to note about the AppDelegate.swift file:

- A fresh install of **iOS capacitor 3.x ends at line 67.**
- The documentation on `@capacitor/push-notifications` has lines 69 ~ 79 but without the `#if USE_PUSH`
- The example app has a lot of extra code below 79:

https://github.com/capacitor-community/fcm/blob/master/example/ios/App/App/AppDelegate.swift#L81

Questions:
1. Do we need to manually add all these methods for the FCM plugin to work? (the stuff below line 81)
2. Do we need to include that `#if USE_PUSH` or not?

I'm sorry to ask so many questions, but I'm not familiar with Swift : S

**Comment by stewones** [comment]
1. no, it's not required
2. yes, but the `#if USE_PUSH` is optional, if you plan to implement push you need the whole block, otherwise you can remove it.

**Comment by stewones** [comment]
just for reference, on Capacitor migration guide they ask to remove the `#if` statement
I didn't remove in the example app but it's working still

![Screen Shot 2021-10-05 at 19 38 37](https://user-images.githubusercontent.com/719763/136113040-61ff7b48-5245-40de-a489-13e72c91af23.png)

**Comment by mesqueeb** [comment]
@stewones thanks for the elaboration!
